server:
    port: 8080
    mode: debug # debug, release, test for gin

database:
    host: localhost
    port: 3306
    username: root
    password: 123123
    dbname: go-mini-admin
    charset: utf8mb4
    max_idle_conns: 10
    max_open_conns: 100

jwt:
    secret: your-super-secret-key-change-in-production
    expire: 24 # hours

log:
    level: debug # debug, info, warn, error
    filename: logs/app.log
    max_size: 100 # MB
    max_backups: 30
    max_age: 7 # days
    compress: true
